#!/bin/sh -f

## a script to run OLMT for simulation using GSWP3_daymet driving forcing and 
## specific domain/surface dataset (generated by 'makepointdata.py'). 

#USER_METDIR=/lustre/or-hydra/cades-ccsi/proj-shared/project_acme/ACME_inputdata
USER_METDIR=/Users/f9y/clm4_5_inputdata
DAYMETTILE=TILE13868

python ./site_fullrun.py \
 --caseidprefix AKSPdaymet \
 --nyears_ad_spinup 100 --nyears_final_spinup 600 --tstep 1 \
 --machine mymac --compiler gnu --mpilib mpich \
 --cpl_bypass --spinup_vars \
 --gswp3 \
 --model_root /Users/f9y/mygithub/E3SM \
 --caseroot /Users/f9y/project_acme/cases \
 --nopointdata \
 --metdir ${USER_METDIR}/atm/datm7/GSWP3_daymet/${DAYMETTILE}/cpl_bypass_full \
 --domainfile ${USER_METDIR}/atm/datm7/GSWP3_daymet/${DAYMETTILE}/cpl_bypass_full/domain.nc \
 --surffile ${USER_METDIR}/atm/datm7/GSWP3_daymet/${DAYMETTILE}/cpl_bypass_full/surfdata.nc \
 --landusefile ${USER_METDIR}/atm/datm7/GSWP3_daymet/${DAYMETTILE}/cpl_bypass_full/surfdata.pftdyn.nc \
 --np 1 \
 --ccsm_input ${USER_METDIR} \
 --runroot /Users/f9y/project_acme/runs

